spring:
  profiles: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update

  logging.level:
    org.hibernate.SQL: debug